### ISSUE TITLE
Sessions and Caching

### ISSUE THREAD

**Issue by stoneliz** [stoneliz/ITC-250-P3-News-Aggregator#1]
Yan,
Did you see Bill's message today about the limitations of session caching. Here's what he said:

In working on P3 we're using sessions to store the cached data for the feeds.  This works great in PHP sessions, but the session data only applies to one user.  What can be done to cache the data for all users instead?

Cache in the database: One way to do that would be to create a database table that stores the cached data.  You could create a table named FeedCache and store the ID of the feed, the data and the date and query the database to see if the data was resident, etc.

Application level variables: In other languages, such as Microsoft's ASP classic, there exists variables that can persist data like a session, however the data is the same for all users.  This is called application level variables.  This treatment would be perfect in our case, as we wish to cache the feed data, which is the same for all users, or for the entire application.

Here is an example of one person's approach to using the file system of PHP to create an application level variable system: http://www.tek-tips.com/faqs.cfm?fid=1825

I'm wondering if you can help us with this since you've already done some good research early on.

**Comment by menyan** [comment]
I am still in LA, I haven’t seen bill’s message yet. I am as confused as you guys are….. I really don’t know how to make this work… I am sorry. I will try to go to class on Tuesday around 12:00 if anybody is available at that time.

**Comment by stoneliz** [comment]
That's ok.


At the very beginning of this project you had uploaded a bunch of code that made us think you had a pretty good understanding of sessions. I didn't quite understand all the algorithms you'd uploaded so I wasn't sure if you'd hit on something that would be helpful.


But if you're confused that's fine, cuz like you said, we are too.


I did some research today and I think i got some insight.


I won't be able to meet at noon because I work right up until I have to commute to the 1pm class but I was hoping to chat with the group after class so if you're able to be there that would be great!


Drag your thoughts away from your troubles... by the ears, by the heels, or any other way you can manage it.
~Mark Twain


________________________________

**Comment by menyan** [comment]
That’s because I used the framework, and i don’t need to write all that the hard way. I can just call it…:(


I am really glad that you got some insight today. Finger crossed we can come up with something.

**Comment by stoneliz** [comment]
I'm not sure I understand what you mean here. It sounds like you found some code that seemed helpful but you weren't totally sure what it did exactly?




Drag your thoughts away from your troubles... by the ears, by the heels, or any other way you can manage it.
~Mark Twain


________________________________

**Comment by stoneliz** [comment]
We got pretty far....
